### ISSUE TITLE
Consider using bump2version instead of bumpversion

### ISSUE THREAD

**Issue by mbjoseph** [pyOpenSci/pyos-package-template#16]
The bumpversion project is no longer maintained (though discussions are ongoing that might resume maintenance). We may want to consider bundling the maintained fork of bumpversion, bump2version: https://github.com/c4urself/bump2version/issues/86

**Comment by xmnlab** [comment]
another option would be rever (https://github.com/regro/rever)
maybe the cookiecutter could ask between bump2version and rever

**Comment by lwasser** [comment]
Friends, I'm closing all of the open issues, given that we have a complete redo of the template now! 🚀! Thank you all for this discussion!! Please reopen this if I'm closing it in error.
