### ISSUE TITLE
adopt a poetry based workflow, describe in tutorial & point to py-pkgs book?

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/pyos-package-template#25]
Currently someone using our cookiecutter will declare dependencies that generate a requirements.txt -- I think this is handled by cookecutter itself on the command line?

Maybe we should consider alternatives, such as `poetry` or `flit`.

Not sure how they would integrate with `cookiecutter` though.
Here's one attempt:
https://github.com/johanvergeer/cookiecutter-poetry

If we do incorporate some external library for dev, probably a good idea to have some more detail on *what* it is and *why* to use it in the tutorial

Would be a very good reason to point to
https://py-pkgs.org

**Comment by NickleDave** [comment]
@ttimbers points out on Twitter that the cookiecutter-ubc-mds in fact already incorporates poetry.
https://twitter.com/TiffanyTimbers/status/1376569796574081025

Maybe we can borrow and/or integrate
https://github.com/UBC-MDS/cookiecutter-ubc-mds

**Comment by xmnlab** [comment]
I think add options for other build system (not sure if it is correct name) would be great. 
maybe setuptools is not the best option, but at least it is still the most common, so maybe it should be the default option.

**Comment by lwasser** [comment]
maybe we have a separate conversation about tools  and options. start by documenting in a hackmd file - get community input,  assess each and go from there?

as i mentioned in  the other issue,  my concern is  dependency mgt and  installation  / envt issues. also a good  idea to figure out what most people are using now as ivan mentions! we  use setuptools  in  all of our tools. this doesn't mean that  it is the  best  option however! 

shall i create a discussion forum here to discuss?  or we could use discourse? boy we have a lot of decisions to make don't we?!!! :)

**Comment by xmnlab** [comment]
for me discussions here is easier :) 

maybe we can create a post on discourse about the discussions here and send the link if anyone is interested in discussion :)

**Comment by NickleDave** [comment]
> for me discussions here is easier :)
> 
> maybe we can create a post on discourse about the discussions here and send the link if anyone is interested in discussion :)

☝️ sounds like a good idea to me

I will post on discourse with a link to discussions if sb sets one up

**Comment by lwasser** [comment]
Friends, I'm closing all of the open issues, given that we have a complete redo of the template now! 🚀! Thank you all for this discussion!! Please reopen this if I'm closing it in error. we are not using poetry!

**Comment by sneakers-the-rat** [comment]
Fwiw I am glad the switch to poetry was not made. 2021 jonny would have been all for it but 2024 jonny has the benefit of hindsight

**Comment by ttimbers** [comment]
@sneakers-the-rat - would love to hear your summary of your hindsight!

**Comment by sneakers-the-rat** [comment]
ha, well the tl;dr of it is i spent several years using it for everything and ignoring others who were grousing that it was too opinionated, and then after trying to contribute several times and the developers being extraordinarily rude for no reason I concluded that highly opinionated might also mean that they have turned off a lot of ppl who want to help out, which is reflected in the contrib stats, and that's why they were falling behind on some features that I needed (multiplatform builds that pull wheels from multiple sources depending on platform in particular, idk if that works now but it didnt then). Then i tried out PDM and was like "oh this is just really nice," switched all my projects and haven't looked back.

**Comment by ttimbers** [comment]
Thanks @sneakers-the-rat ! I appreciate this context.
