### ISSUE TITLE
What should go into the contributing file?

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyos-package-template#29]
The new template for pyOpenSci is awesome. 
The contributing file for it is [here](https://hackmd.io/@lawasser/rJeFZFBxkl/edit). I think we should work as a community towards creating better more modern text that will suit the needs of most new pure python packages that use hatch!

**Comment by Midnighter** [comment]
Please note, that a [contributing doc](https://github.com/pyOpenSci/pyos-package-template/blob/copier/template/%7B%25%20if%20dev_platform%20%3D%3D%20'GitHub'%20%25%7D.github%7B%25%20endif%20%25%7D/CONTRIBUTING.md.jinja) is included, but yet again only for GitHub as the chosen platform.

**Comment by lwasser** [comment]
Oh - i see the file now. it's in the .github folder. I haven't created that file that way before.  i'm going to ping a few others for opinions on this!

```
    create  .github/CODE_OF_CONDUCT.md
    create  .github/SUPPORT.md
    create  .github/CONTRIBUTING.md
```

**Comment by Midnighter** [comment]
It's definitely GitHub-specific and not a general solution. We could have those files in `.github` when the platform is GitHub and in the root of the project otherwise.

**Comment by Midnighter** [comment]
I just checked the [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#about-contributing-guidelines) and they recognize three locations for the contributing guide. In the:

1. project root
2. `docs/`
3. `.github/`

The `docs/` is also a fairly natural location to me, but perhaps comes with a [caveat](https://github.com/pyOpenSci/pyos-package-template/issues/34#issuecomment-2434882639).
