### ISSUE TITLE
Is it possible to have an option to choose VCS versioning over static?

### ISSUE THREAD

**Issue by Midnighter** [pyOpenSci/pyos-package-template#31]
NOTE: Hatch also defaults to VCS, but that is a lot to teach beginners. If there is an option to chose dynamic vs static, it will simplify things for us. 

If this makes for a huge complication, please let me know.

**Comment by lwasser** [comment]
we can merge the open pr and close this issue when it's merged!! the new questions allow us to greatly simplify things.
