### ISSUE TITLE
The project defaults to using mkdocs for documentation but many in the community use sphinx. Could we have a docs option? sphinx vs mkdocs?

### ISSUE THREAD

**Issue by Midnighter** [pyOpenSci/pyos-package-template#34]
I'm torn between two possibilities:

1. Set up the template only with the sphinx configuration as that is what this community recommends. Limit choices and thereby complexity of using the template.
2. Create different options:
    1. Sphinx
    2. mkdocs
    3. no documentation

**Comment by blink1073** [comment]
I like the idea of offering both, but I think we should have a short-circuit option up front that asks if you want to use the default settings for everything that doesn't strictly require input.

**Comment by Midnighter** [comment]
There is one more side-effect of this decision in my opinion. When the documentation is sphinx-based, I probably want to keep the contributing guide, code of conduct, etc. as `.rst` files, such that I can easily include them in the documentation built. Otherwise, I would probably leave them as markdown.

They can certainly exist as duplicates, either in the project instance as both md and rst, one for the repo and one for the docs, or as duplicates in the template where files get included based on user choices. Both come with the usual caveats of duplicating sources.

**Comment by blink1073** [comment]
I would keep the files as .md and use [`myst_parser`](https://github.com/jupyter-server/jupyter_server/blob/74655ce66f36ed85a83591e6658e70ba91232580/docs/source/conf.py#L30)

**Comment by lwasser** [comment]
This is all great discussion. i've definitely kept those files as md files as @blink1073 suggests. I've also included them in my docs using the sphinx `include` directive 

I think we should ensure that these files are included even if the user doesn't use git / github. that brings us to placing them either:

1. in the docs dir or
2. in the root. 

given these are two plaes that are common for them to live. 
What do you both think about 

1. Let's have options for docs  as described above 1) sphinx 2) mkdocs 3) no docs (least preferred)
2. Let's for now keep the contributing, COC, etc files in the project root and see how it goes. I can see positives and draw backs for docs vs root and i don't have a strong opinion. However i did have a look at both [numpy](https://github.com/numpy/numpy) and [scipy](https://github.com/scipy/scipy) and both have contributing at the root. Pandas doesn't! But maybe we follow the core packages here? 
3. I think @blink1073 idea of a short cut is excellent. i'll turn that into a new issue. let's come up with some set of defaults that we think is good and use that too. <new issue - not related here>!!
