### ISSUE TITLE
The template creates both a pyproject.toml and a setup.py file. We can eliminate the setup.py for pure python packaging. can we remove it from the template?

### ISSUE THREAD

**Issue by Midnighter** [pyOpenSci/pyos-package-template#35]
I'm unsure how you created your project from the template, but it does **not** contain a `setup.py` file.

**Comment by lwasser** [comment]
@Midnighter let's close this. I suspect this might have been leah-error where perhaps when i first ran the "cookie" on the latest release it did some odd things. I don't see a setup.py file now. i'll close this as complete / not necessary!
