### ISSUE TITLE
Do we want to use a default python .gitignore file provided by github for the template? this might be a good starting place.

### ISSUE THREAD

**Issue by Midnighter** [pyOpenSci/pyos-package-template#36]
There is [already a file](https://github.com/pyOpenSci/pyos-package-template/blob/main/template/.gitignore) that covers most things Python, but we can, of course, adjust it.

**Comment by lwasser** [comment]
Because this is a template item we could easily edit in the future, let's just use the cookie next week and see how it goes.  Thank you for your patience with my long wishlist of things!!
