### ISSUE TITLE
I'm not sure what the hooks folder that it produces is. Can we please remove that for now? I don't think that needs to be a default but I could be misunderstanding as I am not sure what that is related to a pure python build!

### ISSUE THREAD

**Issue by Midnighter** [pyOpenSci/pyos-package-template#37]
Again, I'm not sure if you ended up running copier on the cookiecutter release. There is no hooks folder in the template.

**Comment by lwasser** [comment]
i'm fairly certain this was a remnant of the other cookie. we can close this!
