### ISSUE TITLE
Error in the pyproject.toml file

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyos-package-template#47]
It looks like there is a spacing issue in the default description value for the pyproject toml. 

```
description = "A project that adds numbers.
"
```

please note that i haven't tested this to see if it's something that I did when i entered the description or something native to the template!

**Comment by lwasser** [comment]
closing this. it's because you have to hit esc to add the description. i accidentally added a line break!

**Comment by Midnighter** [comment]
Either way, it should definitely have triple quotes for being multiline =]

**Comment by lwasser** [comment]
thank you @Midnighter  !!
