### ISSUE TITLE
Start using `partials`/`includes` directory?

### ISSUE THREAD

**Issue by sneakers-the-rat** [pyOpenSci/pyos-package-template#57]
Working on this now, and i can see us getting cluttered pretty quick here :) 

Wondering how people feel if we moved some stuff into a `includes` or `partials` directory? like eg. the contents of the licenses files, where rather than having three literal file stubs within the template directory, we keep the text of the license in a partials directory and then the `LICENSE` file is just a jinja switch on which to include.

That, and macros/partials in something like pyproject.toml with a lot of switching behavior might help keep things tidy.

**Comment by blink1073** [comment]
Makes sense to me!

**Comment by Midnighter** [comment]
Fully agree, the template has blown up considerably in the last week 🚀

**Comment by sneakers-the-rat** [comment]
Great! I have just been doing this in the PRs i've been making, so i'll close this since this was mostly to check in on whether there was some reason *not* to do that :)
