### ISSUE TITLE
Remove requires-python

### ISSUE THREAD

**Issue by ucodery** [pyOpenSci/pyos-package-template#62]
This copier always sets `requires-python = ">=3.10"`, but it doesn't know what versions of python the (yet-to-be-crated) package will be compatible with.

Yes 3.10 is the lowest in-support version, but this is overly-restrictive to users. Especially for use in our tutorials, which use some very vanilla Python that would work all the way back to 3.3 I'd bet.

**Comment by Midnighter** [comment]
@blink1073 mentioned that myst requires 3.10

**Comment by lwasser** [comment]
Oh! This comes from myst? This requirement tripped some people up who were trying to install their package into an existing envt that ran 3.9!

**Comment by ucodery** [comment]
Also, this is adding an _install_ floor to the project for a _documentation_ dependency. At best, it should be a requirement of `tool.hatch.envs.docs`

**Comment by willingc** [comment]
Some discussion about classifiers: https://discuss.python.org/t/handling-stale-python-version-classifiers-for-low-churn-projects/66537/1
