### ISSUE TITLE
Review and test cookiecutter-pyopensci

### ISSUE THREAD

**Issue by kysolvik** [pyOpenSci/pyos-package-template#7]
The basics of cookiecutter-pyopensci are all there and its ready to go! I tried to make the original cookiecutter-pypackage more beginner-friendly while avoiding any significant overhauls. It would be great if someone else could look it over and give it a try. Maybe @mbjoseph or @choldgraf, if either of you are up for it? Here's the [tutorial](https://cookiecutter-pyopensci.readthedocs.io/).

It's currently set up with some example functions and tests, so that after downloading the cookiecutter repo, you can run some example tests. Then users can start adding their own code and tests. Any feedback is appreciated!

Summary of changes from cookiecutter-pypackage:
* Removed option to NOT include an open source license
* Removed option to use Click CLI
* Removed option to NOT use pytest. Defaults to tox & pytest for testing
* Added codecov integration and badge
* Added example functions and tests to give users a starting place
* Added some details and clarification to the tutorial
* Minor tweaks (e.g. replacing cookiecutter-pypackage to cookiecutter-pyopensci throughout the documentation)

**Comment by xmnlab** [comment]
this template is very nice.

I think we should update some pinning. for example related to flake8 https://github.com/PyCQA/pycodestyle/issues/728

**Comment by xmnlab** [comment]
I can open an PR for that.

**Comment by mbjoseph** [comment]
Good point @xmnlab! 

It would be nice to ensure that the deps don't need to be updated in the future.  @lwasser or @kysolvik would it make sense to use PyUp to keep the dev requirements up to date? https://pyup.io/

**Comment by xmnlab** [comment]
would be good to promote here git pre-commit hooks? using for example black, isort, flake8, etc?

**Comment by lwasser** [comment]
Friends, I'm closing all of the open issues, given that we have a complete redo of the template now! 🚀! Thank you all for this discussion!! Please reopen this if I'm closing it in error.
